Added warning to dashboard when using python2

diff --git a/obplayer_check b/obplayer_check
--- a/obplayer_check
+++ b/obplayer_check
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-running_check=`ps -aef | grep "python [o]bplayer.py" | wc -l`
+running_check=`ps -aef | grep "python? [o]bplayer.py" | wc -l`
 
 if [ "$running_check" -ge "1" ]
 then
@@ -15,7 +15,14 @@ if [ ! -x "/usr/bin/python3" ] || ! python3 -c "import apsw"
 then
 	echo "Switching to legacy OpenBroadcaster Player"
 	git checkout legacy
-	exit;
+        if [ $? -ne 0 ]; then
+            echo ""
+            echo "ERROR: failed to switch to the legacy branch.  Python2 is no longer supported.  Please install the Python3 dependencies listed in dependencies.txt of the source file and retry, or check out the \"legacy\" branch from the git repository to continue using Python2"
+            echo ""
+
+            python2 obplayer.py $@
+            exit;
+        fi
 fi
 
 python3 obplayer.py $@
