Temporarily disabled the legacy branch switchover

diff --git a/obplayer_check b/obplayer_check
--- a/obplayer_check
+++ b/obplayer_check
@@ -13,16 +13,15 @@ cd $DIR
 
 if [ ! -x "/usr/bin/python3" ] || ! python3 -c "import apsw"
 then
-	echo "Switching to legacy OpenBroadcaster Player"
-	git checkout legacy
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo "ERROR: failed to switch to the legacy branch.  Python2 is no longer supported.  Please install the Python3 dependencies listed in dependencies.txt of the source file and retry, or check out the \"legacy\" branch from the git repository to continue using Python2"
-            echo ""
+	#echo "Switching to legacy OpenBroadcaster Player"
+	#git checkout legacy
+        #if [ $? -ne 0 ]; then
+        #    echo ""
+        #    echo "ERROR: failed to switch to the legacy branch.  Python2 is no longer supported.  Please install the Python3 dependencies listed in dependencies.txt of the source file and retry, or check out the \"legacy\" branch from the git repository to continue using Python2"
+        #    echo ""
 
-            python2 obplayer.py $@
-        fi
-        exit;
+        python2 obplayer.py $@
+        #fi
+else
+        python3 obplayer.py $@
 fi
-
-python3 obplayer.py $@
